name: "Setup Gradle"
description: |-
  Run the common tasks to setup a Gradle environment from scratch or restoring
  the environment from a previous job:
  - grants execute permissions to the gradlew script
  - set up the JDK
  - set up a Gradle cache for distributed up-to-date checks across jobs so
    Gradle tasks can use the cache by just using the --build-cache option
  Please note that this Action doesn't run any actual command or task other
  than those used to set up the environment. Build commands are to be executed
  after this Action completes.
inputs:
  directory:
    description: |-
      The directory, relative to the repository root and without the trailing
      slash, where the contents for this feature are stored.
      As long as you are using the common project layout you don't need to
      change this directory.
      This directory is used to probe this feature. See the 'probed' output for
      more.
      Default: .
    required: false
    default: '.'
  verbosity:
    description: |-
      Sets the verbosity level to adjust the output logs verbosity.
      Allowed values are: 'error', 'warning', 'quiet', 'info', 'debug'.
      Default: quiet
    required: false
    default: 'quiet'
  cache-mode:
    description: |-
      Whether to enable the cache and, if enabled, how to use it.
      Allowed values are: 'read-write', 'read-only', 'write-only', 'disabled'.
      Default: read-write
    required: false
    default: 'read-write'
  cache-name:
    description: |-
      The name to use for the cache that will be read and/or written by this
      Action.
      If the cache to read does not exists a new one will be created from
      scratch without errors.
      Default: gradle-\$\{\{ github.run_id \}\}
    required: false
    default: 'gradle-${{ github.run_id }}'
  cache-from:
    description: |-
      The cache this Action will read from to initialize the cache defined in
      'cache-name'. The contents of this cache, when it exists, will be imported
      into the cache defined in 'cache-name'.
      If this cache does not exist then 'cache-name' will be started from
      scratch.
      Default: ''
    required: false
    default: ''
  cache-contents:
    description: |-
      The entries to include in the cache.
      You can use a multi-line value here to specify multiple entries.
      Default:
        ~/.gradle/caches
        ~/.gradle/wrapper
        ~/.m2/repository
        .gradle
    required: false
    default: |-
      ~/.gradle/caches
      ~/.gradle/wrapper
      ~/.m2/repository
      .gradle
  install-jdk:
    description: |-
      Whether to install the JDK or not.
      For more see: https://github.com/actions/setup-java.
      Please note that the tools come preinstalled in many hosted GitHub
      runner images and re-installing would just slow down the setup process.
      Consider installing only when the runners don't have it preinstalled or
      when you need a specific version.
      To check out if it's already installed see:
      - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      Default: false
    required: false
    default: 'false'
  install-jdk-distribution:
    description: |-
      The JDK distribution to setup if 'install-jdk' is 'true'.
      For available distributions see: https://github.com/actions/setup-java.
      Default: temurin
    required: false
    default: 'temurin'
  install-jdk-version:
    description: |-
      The JDK version to setup if 'install-jdk' is 'true'.
      For available versions see: https://github.com/actions/setup-java.
      Default: 21
    required: false
    default: '21'
  install-gradle:
    description: |-
      Whether to install Gradle or not.
      For more see: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md.
      Please note that the tools come preinstalled in many hosted GitHub
      runner images and re-installing would just slow down the setup process.
      Consider installing only when the runners don't have it preinstalled or
      when you need a specific version.
      To check out if it's already installed see:
      - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
      Default: false
    required: false
    default: 'false'
  install-gradle-version:
    description: |-
      The Gradle version to setup if 'install-gradle' is 'true'.
      There are a few aliases that can be used here: 'wrapper' uses the version
      defined in the Gradle wrapper (recommended), 'current' uses the latest
      stable release.
      For available versions see: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md.
      Default: wrapper
    required: false
    default: 'wrapper'
outputs:
  probed:
    description: "Returns 'true' if this action has probed the files for this feature."
    value: ${{ steps.probe.outputs.files_exists == 'true' }}
  cache-name:
    description: "The name of the cache key"
    value: ${{ inputs.cache-name }}
runs:
  # Composite GitHub Actions actions require to set 'using': 'composite'
  using: "composite"
  steps:
  - name: List contents used for probing the project
    if: ${{ inputs.verbosity == 'debug' }}
    shell: bash
    continue-on-error: true
    run: |
      echo "::group::Contents used for probing the project"
      ls -alR ${{ inputs.directory }}/gradlew ${{ inputs.directory }}/*.gradle ${{ inputs.directory }}/gradle.*
      echo "::endgroup::"
  - name: Probing the project
    id: probe
    uses: andstor/file-existence-action@v3
    with:
      files: "${{ inputs.directory }}/gradlew ${{ inputs.directory }}/*.gradle ${{ inputs.directory }}/gradle.*"
  - name: Set up the ${{ inputs.cache-name }} read-write cache
    uses: actions/cache@v4
    if: ${{ inputs.cache-mode == 'read-write' }}
    with:
      key: ${{ inputs.cache-name }}
      restore-keys: |-
        ${{ inputs.cache-name }}
        ${{ inputs.cache-from }}
      path: ${{ inputs.cache-contents }}
      enableCrossOsArchive: true
  - name: Set up the ${{ inputs.cache-name }} read-only cache
    uses: actions/cache/restore@v4
    if: ${{ inputs.cache-mode == 'read-only' }}
    with:
      key: ${{ inputs.cache-name }}
      restore-keys: |-
        ${{ inputs.cache-name }}
        ${{ inputs.cache-from }}
      path: ${{ inputs.cache-contents }}
  - name: Set up the ${{ inputs.cache-name }} write-only cache
    uses: actions/cache/save@v4
    if: ${{ inputs.cache-mode == 'write-only' }}
    with:
      key: ${{ inputs.cache-name }}
      path: ${{ inputs.cache-contents }}
  - name: List the cache contents
    if: ${{ inputs.cache-mode != 'disabled' && inputs.verbosity == 'debug' }}
    shell: bash
    continue-on-error: true
    run: |
      echo "::group::Cache contents"
      ls -alR ${{ inputs.cache-contents }}
      echo "::endgroup::"
  # The burrunan/gradle-cache-action@v3 is supposed to be more effective as it provides
  # a distributed multi-layered cache, but it's so unreliable and causes so many cache
  # miss that cause jobs to re-run.
  # So, even if with regular cache (see above) we can't reconcile caches when merging
  # from build paths, at least it's reliable so we only use that.
  #- name: Set up the Gradle distributed cache
  #  uses: burrunan/gradle-cache-action@v3
  #  if: ${{ inputs.cache-mode != 'disabled' && github.ref == 'refs/heads/main' }}
  #  with:
  #    gradle-version: ${{ inputs.install-gradle-version }}
  #    # In order to maximize cache efficiency use a single cache for each workflow run.
  #    job-id: ${{ github.run_id }}
  #    read-only: ${{ inputs.cache-mode == 'read-only' }}
  #    concurrent: true
  #    save-local-build-cache: true
  #    save-generated-gradle-jars: true
  #    save-gradle-dependencies-cache: true
  #    save-maven-dependencies-cache: false
  #    remote-build-cache-proxy-enabled: true
  #    gradle-distribution-sha-256-sum-warning: false
  #    # Arguments must not be declared in order to make it work in cache-only mode.
  #    #arguments:
  - name: Grant execute permission for the 'gradlew' executable and make Git ignore file permissions
    shell: bash
    # We need to make Git ignore execute permission changes to avoid
    # false positives in change detection
    run: |-
      git config core.fileMode false
      chmod +x gradlew
  - name: Setup Java
    uses: mooltiverse/nyx/.github/actions/setup-java@main
    if: ${{ inputs.install-jdk == 'true' }}
    with:
      verbosity: ${{ inputs.verbosity }}
      # No need to setup an extra cache for Java. The Gradle cache is enough.
      install-jdk: ${{ inputs.install-jdk }}
      cache-mode: disabled
      enable-changed-files-detection: false
      install-jdk-distribution: ${{ inputs.install-jdk-distribution }}
      install-jdk-version: ${{ inputs.install-jdk-version }}
  - name: Setup Gradle
    # As long as we use the Gradle wrapper we could not set up Gradle with this
    # action. However, this may be faster than downloading from the internet as
    # it may be already cached in GitHub's infrastructure.
    #
    # This action could be a good option to also setup the Gradle cache but
    # it doesn't allow to set the cache key name so it can't bring the cache
    # across multiple jobs.
    # The plugin is alble to bring the cache over for multiple steps within the
    # same jobs but falls short when it comes to different jobs.
    # This, by the way, makes it somehow useless because tasks running within
    # the same job already share the same worker instance so the Gradle cache
    # is not much of an issue. What the plugin seems good at is with next runs
    # of the same job in the same pipeline (i.e. because of new Git commits),
    # but we rather need to transport a cache between multiple jobs in the same
    # run than the same job on multiple runs.
    #
    # For more see:
    # - https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
    # - https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#cache-keys
    # - https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#finding-a-matching-cache-entry
    uses: gradle/actions/setup-gradle@v4
    if: ${{ inputs.install-gradle == 'true' }}
    with:
      gradle-version: ${{ inputs.install-gradle-version }}
      # Use the custom cache configured above
      cache-disabled: true
      # The build cache report on the Action page is cumbersome, especially
      # when there are many tasks, so let's just print it in case of errors.
      # Valid values are 'always' (default), 'never', and 'on-failure'
      add-job-summary: 'on-failure'
