name: "Setup Docker"
description: |-
  Run the common tasks to setup a Docker environment from scratch or restoring
  the environment from a previous job:
  - set up Docker
  - set up the distributed cache
  - detect file changes
  - enable the containerd image store
  - authenticate to GitHub and ECR container registries
  Please note that this Action doesn't run any actual command or task other
  than those used to set up the environment. Build commands are to be executed
  after this Action completes.
inputs:
  directory:
    description: |-
      The directory, relative to the repository root and without the trailing
      slash, where the contents for this feature are stored.
      As long as you are using the common project layour you don't need to
      change this directory.
      This directory is used to probe this feature. See the 'probed' output for
      more.
      Default: src/docker
    required: false
    default: 'src/docker'
  verbosity:
    description: |-
      Sets the verbosity level to adjust the output logs verbosity.
      Allowed values are: 'error', 'warning', 'quiet', 'info', 'debug'.
      Default: quiet
    required: false
    default: 'quiet'
  enable-cache:
    description: |-
      Whether to enable the cache.
      Default: true
    required: false
    default: 'true'
  cache-name-prefix:
    description: |-
      The prefix of the name to use for the cache that will be read and/or
      written by this Action.
      If the cache to read does not exists a new one will be created from
      scratch without errors.
      Default: docker-\$\{\{ github.run_id \}\}
    required: false
    default: 'docker-${{ github.run_id }}'
  cache-name-suffix:
    description: |-
      The suffix of the name to use for the cache that will be written by this
      Action.
      If the cache to read does not exists a new one will be created from
      scratch without errors.
      In case you want multiple jobs share the same artifacts you can either
      set this value to a generic identifier (which might as well be the
      name of the job that bootstrapped the cache), using the same in all jobs,
      or even leave it empty. What's important for sharing the same artifacts
      is that all jobs use the same value for this attribute, so they use the
      same cache instance.
      Remember, though, that regardless of which job writes the cache, the same
      entry (file) can only be written once in the cache so this means that
      jobs may add new entries but not overwrite existing ones with new versions.
      In the other case, when you need jobs to write new versions of files, you
      need chaining caches, which means one job creates the first cache, then
      others need to read from the previous cache version and create a new cache
      with updated contents.
      When chaining caches, this value should be (or at least include) the ID
      of the Job that writes the cache, while the 'cache-name-restore-suffix'
      has the value of the 'cache-name-suffix' of the job to read the previous
      cache from.
      This allows to chain caches in a way that each job writes its own cache,
      while starting from a previous cache written by some other job.
      Default: \$\{\{ github.job \}\}
    required: false
    default: '${{ github.job }}'
  cache-name-restore-suffix:
    description: |-
      The suffix of the name to use for the cache that will be read by this
      Action.
      If the cache to read does not exists a new one will be created from
      scratch without errors.
      In case you want multiple jobs share the same artifacts just use the
      same value here of the 'cache-name-suffix' attribute used in all jobs
      sharing the cache.
      In the other case, when you need jobs to write new versions of files,
      you need chaining caches, which means one job creates the first cache,
      then others need to read from the previous cache version and create a
      new cache with updated contents. In this case this value must be the
      'cache-name-suffix' of the job to read the previous version of the
      cache from. This way you can start from the previous job's cache and
      create a new version.
      By default this value is the same as 'cache-name-suffix' so as long as
      you don't set this value this cache will be read-only.
      Default: \$\{\{ github.job \}\}
    required: false
    default: '${{ github.job }}'
  cache-contents:
    description: |-
      The entries to include in the cache.
      You can use a multi-line value here to specify multiple entries.
      Default:
        src/docker/**/build
    required: false
    default: |-
      src/docker/**/build
  enable-changed-files-detection:
    description: |-
      Whether to enable the detection of files changed in the workspace for
      the current branch.
      See 'changed-files-filter' for setting the filters to select the files
      to detect changes for.
      Default: true
    required: false
    default: 'true'
  changed-files-pattern:
    description: |-
      The patterns used to match files that have changed.
      If 'enable-changed-files-detection' is true and some of the files matched
      by this filter have changed then the 'changed' output will return 'true',
      'changes_count' will return the number of changed files and 'changed_files'
      will return the list of changed files.
      You can use a multi-line value here to specify multiple entries.
      For more see: https://github.com/marketplace/actions/changed-files.
      Default:
        src/docker/**
        !src/docker/**/build
    required: false
    default: |-
      src/docker/**
      !src/docker/**/build
  enable-containerd-image-store:
    description: |-
      Whether to enable the containerd image store.
      Default: true
    required: false
    default: 'true'
  enable-github-container-registry:
    description: |-
      Whether or not authentication to the GitHub Container Registry must
      be enabled.
      When true the 'github-user' and the 'github-token' will be used to
      authenticate.
      Default: false
    required: false
    default: 'false'
  github-user:
    description: |-
      The GitHub user to use for remote API.
      When using the GITHUB_TOKEN this may be anything.
      See 'enable-github-container-registry' to enable authentication.
    required: false
    default: ''
  github-token:
    description: |-
      The GitHub token to use for remote API.
      This should be the value of the secret \$\{\{ secrets.GITHUB_TOKEN \}\}.
      See 'enable-github-container-registry' to enable authentication.
    required: false
    default: ''
  enable-elastic-container-registry:
    description: |-
      Whether or not authentication to the AWS Elastic Container Registry (ECR)
      must be enabled.
      When true the 'aws-region', 'aws-access-key-id' and 'aws-secret-access-key'
      will be used to authenticate to the registry identified by
      'aws-container-registry'.
      Default: false
    required: false
    default: 'false'
  aws-region:
    description: |-
      The AWS region to use for remote API.
      This is usually the value of the AWS_REGION environment variable.
      See 'enable-elastic-container-registry' to enable authentication.
    required: false
    default: ''
  aws-container-registry:
    description: |-
      The AWS Elastic Container Registry fully qualified name (i.e.
      '<aws-account-number>.dkr.ecr.<region>.amazonaws.com').
      See 'enable-elastic-container-registry' to enable authentication.
    required: false
    default: ''
  aws-access-key-id:
    description: |-
      The AWS access key ID to use for remote API.
      This is usually the value of the AWS_ACCESS_KEY_ID environment variable.
      See 'enable-elastic-container-registry' to enable authentication.
    required: false
    default: ''
  aws-secret-access-key:
    description: |-
      The AWS access key ID to use for remote API.
      This is usually the value of the AWS_SECRET_ACCESS_KEY environment variable.
      See 'enable-elastic-container-registry' to enable authentication.
    required: false
    default: ''
outputs:
  probed:
    description: "Returns 'true' if this action has probed the files for this feature."
    value: ${{ steps.probe.outputs.files_exists == 'true' }}
  cache-name:
    description: "The name of the cache key"
    value: ${{ inputs.cache-name-prefix }}-${{ inputs.cache-name-suffix }}
  cache-name-suffix:
    description: "The value of the 'cache-name-suffix'"
    value: ${{ inputs.cache-name-suffix }}
  changed:
    description: "Returns 'true' if the 'enable-changed-files-detection' input is true and some files defined in the 'changed-files-filter' input have changed"
    value: ${{ inputs.enable-changed-files-detection == 'true' && steps.changes.outputs.any_changed || 'false' }}
  changes_count:
    description: "Returns the number of changed files if the 'enable-changed-files-detection' input is true and some files defined in the 'changed-files-filter' input have changed"
    value: ${{ inputs.enable-changed-files-detection == 'true' && steps.changes.outputs.all_changed_and_modified_files_count || '0' }}
  changed_files:
    description: "Returns the list of changed files if the 'enable-changed-files-detection' input is true and some files defined in the 'changed-files-filter' input have changed"
    value: ${{ inputs.enable-changed-files-detection == 'true' && steps.changes.outputs.all_changed_and_modified_files || '' }}
runs:
  # Composite GitHub Actions actions require to set 'using': 'composite'
  using: "composite"
  steps:
  - name: List contents used for probing the project
    if: ${{ inputs.verbosity == 'debug' }}
    shell: bash
    continue-on-error: true
    run: |
      echo "::group::Contents used for probing the project"
      ls -alR ${{ inputs.directory }}/* ${{ inputs.directory }}/**/*
      echo "::endgroup::"
  - name: Probing the project
    id: probe
    uses: andstor/file-existence-action@v3
    with:
      files: "${{ inputs.directory }}/* ${{ inputs.directory }}/**/*"
  - name: Set up the ${{ inputs.cache-name-prefix }}-${{ inputs.cache-name-suffix }} cache
    uses: actions/cache@v4
    if: ${{ inputs.enable-cache == 'true' }}
    with:
      key: ${{ inputs.cache-name-prefix }}-${{ inputs.cache-name-suffix }}
      restore-keys: |-
        ${{ inputs.cache-name-prefix }}-${{ inputs.cache-name-restore-suffix }}
      path: ${{ inputs.cache-contents }}
      enableCrossOsArchive: true
  - name: List the cache contents
    if: ${{ inputs.enable-cache == 'true' && inputs.verbosity == 'debug' }}
    shell: bash
    continue-on-error: true
    run: |
      echo "::group::Cache contents"
      ls -alR ${{ inputs.cache-contents }}
      echo "::endgroup::"
  - name: Detect file changes
    uses: tj-actions/changed-files@v45
    if: ${{ inputs.enable-changed-files-detection == 'true' }}
    id: changes
    with:
      files: |
        ${{ inputs.changed-files-pattern }}
  - name: List changed files
    if: ${{ inputs.enable-changed-files-detection == 'true' && (inputs.verbosity == 'info' || inputs.verbosity == 'debug') }}
    shell: bash
    continue-on-error: true
    env:
      ALL_CHANGED_FILES: ${{ steps.changes.outputs.all_changed_and_modified_files }}
    run: |
      echo ${{ steps.changes.outputs.all_changed_and_modified_files_count }} files have changed.
      for file in ${ALL_CHANGED_FILES}; do
        echo "$file"
      done
  - name: Enable the containerd image store
    uses: crazy-max/ghaction-setup-docker@v3
    if: ${{ inputs.enable-containerd-image-store == 'true' }}
    with:
      daemon-config: |-
        {
          "features": {
            "containerd-snapshotter": true
          }
        }
  - name: Show the Docker driver
    # When the 'containerd' image store is used the output looks like:
    #   [[driver-type io.containerd.snapshotter.v1]]
    if: ${{ inputs.enable-containerd-image-store == 'true' && (inputs.verbosity == 'info' || inputs.verbosity == 'debug') }}
    shell: bash
    continue-on-error: true
    run: docker info -f '{{ .DriverStatus }}'
  - name: Log in to the GitHub Container Registry
    uses: docker/login-action@v3
    if: ${{ inputs.enable-github-container-registry == 'true' }}
    with:
      registry: ghcr.io
      username: ${{ inputs.github-user }}
      password: ${{ inputs.github-token }}
  - name: Authenticating to AWS in region ${{ inputs.aws-region }} with access key ${{ inputs.aws-access-key-id }}
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.enable-elastic-container-registry == 'true' }}
    with:
      aws-region: ${{ inputs.aws-region }}
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
  - name: Log in to the AWS Elastic Container Registry
    uses: docker/login-action@v3
    if: ${{ inputs.enable-elastic-container-registry == 'true' }}
    with:
      registry: ${{ inputs.aws-container-registry }}
  #- name: Log in to the AWS Elastic Container Registry
  #  uses: aws-actions/amazon-ecr-login@v2
  #  if: ${{ inputs.enable-elastic-container-registry == 'true' }}
  #  # Multiple account IDs may be passed to set registries.
  #  # The default ECR Private registry is assumed.
  #  # See: https://github.com/aws-actions/amazon-ecr-login/blob/main/action.yml
