source "https://rubygems.org"

# The following is the only gem required when using the theme as remote_theme (see _config.yml)
gem "github-pages", group: :jekyll_plugins

# The following shoudl't be needed but... it is. See https://github.com/mmistakes/minimal-mistakes/issues/1937
gem "jekyll-include-cache", group: :jekyll_plugins