import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Configure the sidebars for the '@docusaurus/plugin-docs' plugin.
// The 'docs' plugin is configured.
//
// Sidebars can be generated from the filesystem, or explicitly defined here.
// Here you can create as many sidebars as you want.
// When configuring sidebars remember that:
// - the 'dirName' path is relative to the 'docs' directory. If you want to
//   auto generate a sidebar with the entire contents of the 'docs' directory
//   just set the 'dirName' path to '.'
//
// For more see:
// - https://docusaurus.io/docs/sidebar
// - https://docusaurus.io/docs/sidebar/items
// - https://docusaurus.io/docs/sidebar/multiple-sidebars
const sidebars: SidebarsConfig = {
  userGuideSidebar: [
    // The 'User' sidebar, generated dynamically by contents in the
    // 'docs/user' directory.
    {
      type: 'autogenerated',
      dirName: 'user',
    }
  ],
  developerGuideSidebar: [
    // The 'Developer' sidebar, generated dynamically by contents in the
    // 'docs/developer' directory.
    {
      type: 'autogenerated',
      dirName: 'developer',
    }
  ],
  resourcesSidebar: [
    // The 'Resources' sidebar, generated dynamically by contents in the
    // 'docs/resources' directory.
    {
      type: 'autogenerated',
      dirName: 'resources',
    }
  ],
};

export default sidebars;
