# Run Java tests in a job sequence.
#
# This workflow runs unit, integration and functional tests in separate
# jobs and is well suited for medium and large test suites.
# Execution is performed in the unit > integration > functional test
# sequence so each job only runs if the previous is successful.
# For smaler suites see the 'java-test-compact.yml' workflow.

name: Java Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      runs-on:
        description: |-
          Define the type of machine to run the job on.
          Default: ubuntu-latest
        type: string
        required: false
        default: 'ubuntu-latest'
      verbosity:
        description: |-
          Sets the verbosity level to adjust the output logs verbosity.
          Allowed values are: 'error', 'warning', 'quiet', 'info', 'debug'.
          Default: quiet
        type: string
        required: false
        default: 'quiet'
      gradle-arguments:
        description: |-
          The whitespace separated list of Gradle arguments to pass on the
          Gradle command line. See also 'gradle-secret-arguments' for passing
          sensitive values.
          For example you may use '--quiet', '--warn', '--info', '--debug' to
          set the verbosity level.
          For more see: https://docs.gradle.org/current/userguide/command_line_interface.html.
          Default: --build-cache --stacktrace'
        type: string
        required: false
        default: "--build-cache --stacktrace"
      gradle-unit-test-tasks:
        description: |-
          The whitespace separated list of Gradle tasks to run for
          Unit Tests.
          Default: src:java:unitTest
        type: string
        required: false
        default: "src:java:unitTest"
      gradle-integration-test-tasks:
        description: |-
          The whitespace separated list of Gradle tasks to run for
          Integration Tests.
          Default: src:java:integrationTest
        type: string
        required: false
        default: "src:java:integrationTest"
      gradle-functional-test-tasks:
        description: |-
          The whitespace separated list of Gradle tasks to run for
          Functional Tests.
          Default: src:java:functionalTest
        type: string
        required: false
        default: "src:java:functionalTest"
      artifacts-name-prefix:
        description: |-
          The prefix to use for the name of artifacts published by
          the workflow.
          This might be useful when using this workflow with a matrix
          strategy and you need to avoid overlapping names in artifact
          names published by multiple instances of the workflow.
          Default: java
        type: string
        required: false
        default: "java"
      install-jdk:
        description: |-
          Whether to install the JDK or not.
          For more see: https://github.com/actions/setup-java.
          Please note that the tools come preinstalled in many hosted GitHub
          runner images and re-installing would just slow down the setup process.
          Consider installing only when the runners don't have it preinstalled or
          when you need a specific version.
          To check out if it's already installed see:
          - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
          Default: false
        type: boolean
        required: false
        default: true
      install-jdk-distribution:
        description: |-
          The JDK distribution to setup if 'install-jdk' is 'true'.
          For available distributions see: https://github.com/actions/setup-java.
          Default: temurin
        type: string
        required: false
        default: 'temurin'
      install-jdk-version:
        description: |-
          The JDK version to setup if 'install-jdk' is 'true'.
          For available versions see: https://github.com/actions/setup-java.
          Default: 21
        type: string
        required: false
        default: '21'
      install-gradle:
        description: |-
          Whether to install Gradle or not.
          For more see: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md.
          Please note that the tools come preinstalled in many hosted GitHub
          runner images and re-installing would just slow down the setup process.
          Consider installing only when the runners don't have it preinstalled or
          when you need a specific version.
          To check out if it's already installed see:
          - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
          Default: false
        type: boolean
        required: false
        default: false
      install-gradle-version:
        description: |-
          The Gradle version to setup if 'install-gradle' is 'true'.
          There are a few aliases that can be used here: 'wrapper' uses the version
          defined in the Gradle wrapper (recommended), 'current' uses the latest
          stable release.
          For available versions see: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md.
          Default: wrapper
        type: string
        required: false
        default: 'wrapper'
      install-node:
        description: |-
          Whether to install Node or not.
          For more see: https://github.com/actions/setup-node.
          Please note that the tools come preinstalled in many hosted GitHub
          runner images and re-installing would just slow down the setup process.
          Consider installing only when the runners don't have it preinstalled or
          when you need a specific version.
          To check out if it's already installed see:
          - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
          Default: false
        type: boolean
        required: false
        default: false
      install-node-version:
        description: |-
          The Node SDK version to setup if 'install-node' is 'true'.
          For available versions see: https://github.com/actions/setup-node.
          Default: latest
        type: string
        required: false
        default: 'latest'
      install-newman:
        description: |-
          Whether to install Newman or not.
          For more see: https://learning.postman.com/docs/collections/using-newman-cli/installing-running-newman/.
          Default: false
        type: boolean
        required: false
        default: false
      nyx-cache-name-restore-suffix:
        description: |-
          The suffix of the name to use for the cache that will be read by this
          workflow. This is useful to 'chain' caches, so here you can pass the
          suffix from a previous cache to make this workflow start from that
          one cache.
          If the cache to read does not exists a new one will be created from
          scratch without errors.
          Default: none
        type: string
        required: false
        default: ""
      gradle-cache-name-prefix:
        description: |-
          The prefix to use for the cache that will be read by this workflow.
          This is useful to 'chain' caches, so here you can pass the suffix
          from a previous cache to make this workflow start from that one cache.
          Moreover, this can be used to override the default Gradle action's
          cache prefix to make all jobs within the same stream (i.e. a feature)
          share the same prefix and not overlap with other streams. However,
          when setting this prefix to some specific feature you won't be
          able to merge the caches and in case you 'chain' them you can only
          use one upstream cache for each downstream job.
          If the cache to read does not exists a new one will be created from
          scratch without errors.
          Default: gradle-\$\{\{ github.job \}\}-java (isolate the cache for
          the 'java' feature).
        type: string
        required: false
        default: "gradle-${{ github.run_id }}-java"
      gradle-cache-name-restore-suffix:
        description: |-
          The suffix of the name to use for the cache that will be read by this
          workflow. This is useful to 'chain' caches, so here you can pass the
          suffix from a previous cache to make this workflow start from that
          one cache.
          If the cache to read does not exists a new one will be created from
          scratch without errors.
          Default: \$\{\{ github.job \}\}
        type: string
        required: false
        default: "${{ github.job }}"
      java-cache-name-restore-suffix:
        description: |-
          The suffix of the name to use for the cache that will be read by this
          workflow. This is useful to 'chain' caches, so here you can pass the
          suffix from a previous cache to make this workflow start from that
          one cache.
          If the cache to read does not exists a new one will be created from
          scratch without errors.
          Default: \$\{\{ github.job \}\}
        type: string
        required: false
        default: "${{ github.job }}"
    secrets:
      gradle-secret-arguments:
        description: |-
          The whitespace separated list of Gradle arguments to pass on the
          Gradle command line. This is for passing sensitive values.
          See also 'gradle-arguments' for passing non sensitive values.
          For example you may use '--quiet', '--warn', '--info', '--debug' to
          set the verbosity level.
          For more see: https://docs.gradle.org/current/userguide/command_line_interface.html.
        required: false
    outputs:
      gradle-cache-name-suffix:
        description: "The suffix of the name used by the last cache in this workflow. This is useful to 'chain' caches, so you can pass this value as input for other actions or workflows."
        value: ${{ jobs.test-functional.outputs.gradle-cache-name-suffix }}
      java-cache-name-suffix:
        description: "The suffix of the name used by the last cache in this workflow. This is useful to 'chain' caches, so you can pass this value as input for other actions or workflows."
        value: ${{ jobs.test-functional.outputs.java-cache-name-suffix }}

env:
  # Compute the extra Gradle properties to use for Gradle commands.
  # Here:
  # - we add one argument for the verbosity level passed in the 'verbosity' input
  GRADLE_EXTRA_OPTS: >-
    ${{ inputs.verbosity == 'warning' && '--warn' || '' }}
    ${{ inputs.verbosity == 'quiet' && '--quiet' || '' }}
    ${{ inputs.verbosity == 'info' && '--info' || '' }}
    ${{ inputs.verbosity == 'debug' && '--debug' || '' }}

jobs:
  test-unit:
    name: Unit Test
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: mooltiverse/nyx/.github/actions/setup-git@main
      with:
        verbosity: ${{ inputs.verbosity }}
    - id: nyx
      uses: mooltiverse/nyx/.github/actions/setup-nyx@main
      with:
        # Just restore the cache
        enable-action: false
        verbosity: ${{ inputs.verbosity }}
        cache-name-restore-suffix: ${{ inputs.nyx-cache-name-restore-suffix }}
    - id: java
      uses: mooltiverse/nyx/.github/actions/setup-java@main
      with:
        verbosity: ${{ inputs.verbosity }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ inputs.java-cache-name-restore-suffix }}
    - id: node
      if: inputs.node-cache-name-restore-suffix != ''
      uses: mooltiverse/toolbox/.github/actions/setup-node@main
      with:
        verbosity: ${{ inputs.verbosity }}
        install-node: ${{ inputs.install-node }}
        install-node-version: ${{ inputs.install-node-version }}
        install-newman: ${{ inputs.install-newman }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ inputs.node-cache-name-restore-suffix }}
    - id: gradle
      uses: mooltiverse/nyx/.github/actions/setup-gradle@main
      with:
        verbosity: ${{ inputs.verbosity }}
        install-jdk: ${{ inputs.install-jdk }}
        install-jdk-version: ${{ inputs.install-jdk-version }}
        install-jdk-distribution: ${{ inputs.install-jdk-distribution }}
        install-gradle: ${{ inputs.install-gradle }}
        install-gradle-version: ${{ inputs.install-gradle-version }}
        cache-name-prefix: ${{ inputs.gradle-cache-name-prefix }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ inputs.gradle-cache-name-restore-suffix }}
    - name: Run Unit Tests the on Java code
      shell: bash
      run: ./gradlew ${{ inputs.gradle-arguments }} ${{ secrets.gradle-secret-arguments }} ${{ env.GRADLE_EXTRA_OPTS }} ${{ inputs.gradle-unit-test-tasks }}
    - name: Publish the unit test report artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: ${{ inputs.artifacts-name-prefix }}-${{ github.job }}-reports
        path: src/java/**/build/test/unit/
    outputs:
      java-cache-name-suffix: ${{ steps.java.outputs.cache-name-suffix }}
      gradle-cache-name-suffix: ${{ steps.gradle.outputs.cache-name-suffix }}

  test-integration:
    name: Integration Test
    needs:
    - test-unit
    runs-on: ${{ inputs.runs-on }}
    # Avoid jobs invoking remote services to run in parallel to avoid throttling
    # down by those services (with consequent test failures).
    # See https://github.com/mooltiverse/nyx/issues/206 for more
    concurrency:
      group: access-to-rate-limited-remote-services
      cancel-in-progress: false
    steps:
    - uses: mooltiverse/nyx/.github/actions/setup-git@main
      with:
        verbosity: ${{ inputs.verbosity }}
    - id: nyx
      uses: mooltiverse/nyx/.github/actions/setup-nyx@main
      with:
        # Just restore the cache
        enable-action: false
        verbosity: ${{ inputs.verbosity }}
        cache-name-restore-suffix: ${{ inputs.nyx-cache-name-restore-suffix }}
    - id: java
      uses: mooltiverse/nyx/.github/actions/setup-java@main
      with:
        verbosity: ${{ inputs.verbosity }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ needs.test-unit.outputs.java-cache-name-suffix }}
    - id: gradle
      uses: mooltiverse/nyx/.github/actions/setup-gradle@main
      with:
        verbosity: ${{ inputs.verbosity }}
        install-jdk: ${{ inputs.install-jdk }}
        install-jdk-version: ${{ inputs.install-jdk-version }}
        install-jdk-distribution: ${{ inputs.install-jdk-distribution }}
        install-gradle: ${{ inputs.install-gradle }}
        install-gradle-version: ${{ inputs.install-gradle-version }}
        cache-name-prefix: ${{ inputs.gradle-cache-name-prefix }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ needs.test-unit.outputs.gradle-cache-name-suffix }}
    - name: Run Integration Tests on Java code
      shell: bash
      run: ./gradlew ${{ inputs.gradle-arguments }} ${{ secrets.gradle-secret-arguments }} ${{ env.GRADLE_EXTRA_OPTS }} ${{ inputs.gradle-integration-test-tasks }}
    - name: Publish the integration test report artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: ${{ inputs.artifacts-name-prefix }}-${{ github.job }}-reports
        path: src/java/**/build/test/integration/
    outputs:
      java-cache-name-suffix: ${{ steps.java.outputs.cache-name-suffix }}
      gradle-cache-name-suffix: ${{ steps.gradle.outputs.cache-name-suffix }}

  test-functional:
    name: Functional Test
    needs:
    - test-integration
    runs-on: ${{ inputs.runs-on }}
    # Avoid jobs invoking remote services to run in parallel to avoid throttling
    # down by those services (with consequent test failures).
    # See https://github.com/mooltiverse/nyx/issues/206 for more
    concurrency:
      group: access-to-rate-limited-remote-services
      cancel-in-progress: false
    steps:
    - uses: mooltiverse/nyx/.github/actions/setup-git@main
      with:
        verbosity: ${{ inputs.verbosity }}
    - id: nyx
      uses: mooltiverse/nyx/.github/actions/setup-nyx@main
      with:
        # Just restore the cache
        enable-action: false
        verbosity: ${{ inputs.verbosity }}
        cache-name-restore-suffix: ${{ inputs.nyx-cache-name-restore-suffix }}
    - id: java
      uses: mooltiverse/nyx/.github/actions/setup-java@main
      with:
        verbosity: ${{ inputs.verbosity }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ needs.test-integration.outputs.java-cache-name-suffix }}
    - id: gradle
      uses: mooltiverse/nyx/.github/actions/setup-gradle@main
      with:
        verbosity: ${{ inputs.verbosity }}
        install-jdk: ${{ inputs.install-jdk }}
        install-jdk-version: ${{ inputs.install-jdk-version }}
        install-jdk-distribution: ${{ inputs.install-jdk-distribution }}
        install-gradle: ${{ inputs.install-gradle }}
        install-gradle-version: ${{ inputs.install-gradle-version }}
        cache-name-prefix: ${{ inputs.gradle-cache-name-prefix }}
        # Restore the cache from the previous job to 'chain' the two caches
        cache-name-restore-suffix: ${{ needs.test-integration.outputs.gradle-cache-name-suffix }}
    - name: Run Functional Tests on Java code
      shell: bash
      run: ./gradlew ${{ inputs.gradle-arguments }} ${{ secrets.gradle-secret-arguments }} ${{ env.GRADLE_EXTRA_OPTS }} ${{ inputs.gradle-functional-test-tasks }}
    - name: Publish the functional test report artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: ${{ inputs.artifacts-name-prefix }}-${{ github.job }}-reports
        path: src/java/**/build/test/functional/
    outputs:
      java-cache-name-suffix: ${{ steps.java.outputs.cache-name-suffix }}
      gradle-cache-name-suffix: ${{ steps.gradle.outputs.cache-name-suffix }}
